name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  php-composer:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: dmyst3/PHP_Composer/.github/workflows/main.yml@main
        with:
          namet: "AHMAD"
